import { useEffect, useMemo, useRef, useState } from 'react';
import { readUrlContent } from '../../system/contentModel.js';
import { ExperienceSoundscape, ExperienceVideo, useExperienceMedia } from '../media/ExperienceMedia.jsx';
import './skyPromiseReborn.css';

const FALLBACKS=['https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80'];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function pulse(strong=false){try{navigator.vibrate?.(strong?[8,20,12]:[4])}catch{}}

function Stars({dawn=0}){const ref=useRef(null);useEffect(()=>{const c=ref.current,ctx=c?.getContext('2d');if(!ctx)return;let raf=0,dead=false;const stars=Array.from({length:120},()=>({x:Math.random(),y:Math.random()*.8,r:.4+Math.random()*1.6,a:.28+Math.random()*.7,t:Math.random()*6.28}));const resize=()=>{const d=Math.min(devicePixelRatio||1,1.4);c.width=c.clientWidth*d;c.height=c.clientHeight*d;ctx.setTransform(d,0,0,d,0,0)};resize();const ro=new ResizeObserver(resize);ro.observe(c);const draw=now=>{if(dead)return;const w=c.clientWidth,h=c.clientHeight;ctx.clearRect(0,0,w,h);stars.forEach(s=>{const a=s.a*(1-dawn*.92)*(.8+Math.sin(now*.001+s.t)*.2);ctx.fillStyle=`rgba(232,241,255,${Math.max(0,a)})`;ctx.beginPath();ctx.arc(s.x*w,s.y*h,s.r,0,Math.PI*2);ctx.fill()});raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>{dead=true;cancelAnimationFrame(raf);ro.disconnect()}},[dawn]);return <canvas ref={ref} className="spr-stars" aria-hidden="true"/>}

function Horizon({onProgress,onDone}){const start=useRef(null),done=useRef(false),[p,setP]=useState(0);const down=e=>{start.current=e.clientY;e.currentTarget.setPointerCapture?.(e.pointerId)};const move=e=>{if(start.current==null||done.current)return;const n=clamp((start.current-e.clientY)/220,0,1);setP(n);onProgress(n);if(n>.95){done.current=true;pulse(true);setTimeout(onDone,600)}};return <button className="spr-horizon-control" style={{'--p':p}} aria-label="Tunni tongga aylantirish uchun yuqoriga suring" onPointerDown={down} onPointerMove={move} onPointerUp={()=>start.current=null} onPointerCancel={()=>start.current=null} onKeyDown={e=>{if((e.key==='Enter'||e.key===' ')&&!done.current){e.preventDefault();done.current=true;setP(1);onProgress(1);setTimeout(onDone,600)}}}><i/><b>↑</b><span>{Math.round(p*100)}%</span></button>}

export function SkyPromiseReborn({content:contentProp=null,media={},embedded=false}){
 const content=useMemo(()=>contentProp||readUrlContent('proposal-sky'),[contentProp]);const assets=useExperienceMedia(media);const photos=assets.photos.length?assets.photos:FALLBACKS;const [phase,setPhase]=useState('night');const [stars,setStars]=useState([]);const [dawn,setDawn]=useState(0);
 const choose=i=>{if(stars.includes(i))return;const n=[...stars,i];setStars(n);pulse();if(n.length===3)setTimeout(()=>setPhase(assets.video?'meteor':'horizon'),800)};
 return <main className={'sky-promise-reborn '+(embedded?'is-embedded ':'')+'phase-'+phase} style={{'--dawn':dawn}}>
  <ExperienceSoundscape preset={content.musicPreset||'Dream'} customUrl={assets.music} startAt={content.musicStart||0}/><div className="spr-atmosphere"/><Stars dawn={dawn}/><div className="spr-horizon-glow"/><div className="spr-grain"/><div className="spr-vignette"/>
  <header className="spr-chrome"><a href="?">emora<span>.</span></a><small>SKY PROMISE · BEFORE SUNRISE</small><b>{phase==='night'?'00':phase==='meteor'?'01':phase==='horizon'?'02':'03'}</b></header>
  <section className="spr-stage spr-night"><article><p>THREE STARS · THREE MEMORIES</p><h1>{content.message||'Tong otishidan oldin osmon uchta xotirani ko‘rsatadi.'}</h1><em>{content.recipient}</em></article><svg className={'spr-lines count-'+stars.length} viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path pathLength="1" d="M26 42 L52 22 L76 47"/></svg><div className="spr-portals">{[{x:26,y:42},{x:52,y:22},{x:76,y:47}].map((s,i)=><button key={i} className={stars.includes(i)?'selected':''} style={{left:s.x+'%',top:s.y+'%'}} aria-label={(i+1)+'-yulduzni oching'} onClick={()=>choose(i)}><i/><div><img src={photos[i]} alt=""/><span>{content.captions?.[i]||['Boshlanish.','Bizning eng yaxshi tunimiz.','Keyingi tong.'][i]}</span></div></button>)}</div></section>
  <section className="spr-stage spr-meteor"><div className="spr-meteor-streak"/><div className="spr-video"><ExperienceVideo src={assets.video} poster={photos[1]} title="Meteor message" autoReveal onEnded={()=>setPhase('horizon')}/></div><button onClick={()=>setPhase('horizon')}>Tongga o‘tish →</button></section>
  <section className="spr-stage spr-horizon"><article><p>02 · MOVE THE HORIZON</p><h2>Tunni yuqoriga sur.</h2><span>{content.recipient}</span></article><Horizon onProgress={setDawn} onDone={()=>setPhase('sunrise')}/></section>
  <section className="spr-stage spr-sunrise"><div className="spr-sun"/><div className="spr-rays"><i/><i/><i/><i/></div><article><p>A NEW DAY STARTS HERE</p><h2>{content.final||'Har tongni sen bilan kutib olishimga rozimisan?'}</h2><em>{content.recipient}</em><div><button>HA</button><button onClick={()=>location.reload()}>Qayta ko‘rish ↺</button></div></article></section>
 </main>
}
