export const EXPERIENCES=[
 {slug:'love-rose',group:'LOVE',name:'Rose Theatre',ritual:'curtain',tone:'rose',eyebrow:'YURAK SAHNASI',intro:'Ba’zi hikoyalar parda ochilganda boshlanadi.',instruction:'Pardani oching',messages:['Seni ko‘rgan kunim sahna yorishgandek bo‘lgan.','Har bir xotira — men qayta ko‘rishni istaydigan kadr.','Bu hikoyada eng sevimli qahramonim — sensan.'],final:'Bu sahna tugamaydi. Men seni yana va yana tanlayman.'},
 {slug:'love-pearl',group:'LOVE',name:'Pearl Linen',ritual:'envelope',tone:'pearl',eyebrow:'MAXFIY MAKTUB',intro:'Senga yozilgan bir gap hali ochilmagan.',instruction:'Muhrni sindiring',messages:['Bu maktub shoshilmay ochilishi kerak.','Satrlar orasida men aytolmagan gaplar bor.','Eng qimmat so‘z ichkarida yashiringan.'],final:'Senga aytmoqchi bo‘lganim juda oddiy: sen men uchun alohidasan.'},
 {slug:'love-galaxy',group:'LOVE',name:'Galaxy Confession',ritual:'galaxy',tone:'galaxy'},
 {slug:'wedding-silk',group:'WEDDING',name:'Silk Heritage',ritual:'silk',tone:'silk',eyebrow:'BIR KUN · BIR AHД',intro:'Ikki yo‘l bir kun kelib bitta naqshga aylanadi.',instruction:'Ipakni oching',messages:['Ikki ism. Bitta hikoya.','Sana — yuraklar eslab qoladigan belgi.','Yaqinlar duosi bilan yangi bob boshlanadi.'],final:'Sizni bu kunning eng qadrli guvohi sifatida kutamiz.'},
 {slug:'wedding-garden',group:'WEDDING',name:'Night Garden',ritual:'garden',tone:'garden',eyebrow:'TUNGI BOG‘',intro:'Bugun kechasi bog‘ faqat siz uchun uyg‘onadi.',instruction:'Chiroqlarni yoqing',messages:['Birinchi chiroq — uchrashuvimiz uchun.','Ikkinchisi — oilalarimiz uchun.','Uchinchisi — boshlanayotgan yo‘l uchun.'],final:'Bog‘ yondi. Endi sizning kelishingizgina qoldi.'},
 {slug:'wedding-naqsh',group:'WEDDING',name:'Heritage Naqsh',ritual:'naqsh',tone:'naqsh',eyebrow:'NAQSHDA YOZILGAN KUN',intro:'Har bir nuqta qo‘shilganda naqsh to‘liq bo‘ladi.',instruction:'4 nuqtani birlashtiring',messages:['Ismlar naqsh markazida uchrashadi.','Sana geometrik ritmga aylanadi.','Har bir chiziq — avlodlardan kelgan duo.'],final:'Naqsh to‘liq. Endi marosim siz bilan mukammal.'},
 {slug:'birthday-aurora',group:'BIRTHDAY',name:'Aurora Paper',ritual:'gift',tone:'aurora',eyebrow:'BIR KUNLIK MO‘JIZA',intro:'Bu sovg‘a ichida buyum emas, kayfiyat bor.',instruction:'Qutini oching',messages:['Birinchi qatlam — kulgi uchun.','Ikkinchi qatlam — yangi orzular uchun.','Oxirgi qatlam — sen bo‘lganing uchun.'],final:'Bugun osmon ham seni tabriklaydi. Tug‘ilgan kuning bilan!'},
 {slug:'birthday-balloon',group:'BIRTHDAY',name:'Balloon Dream',ritual:'balloons',tone:'balloon',eyebrow:'HAVODAGI TILAKLAR',intro:'Uchta shar ichida uchta yashirin tilak bor.',instruction:'3 sharni yorib chiqing',messages:['Ko‘proq kulgi.','Ko‘proq sarguzasht.','Ko‘proq o‘zing bo‘lish uchun jasorat.'],final:'Barcha tilaklar osmonga chiqdi. Tug‘ilgan kuning bilan!'},
 {slug:'birthday-memory',group:'BIRTHDAY',name:'Memory Reel',ritual:'reel',tone:'reel',eyebrow:'XOTIRALAR KINOSI',intro:'Ba’zi tug‘ilgan kunlar filmdek qayta ko‘riladi.',instruction:'Reelni aylantiring',messages:['Bir kadr — bir kulgi.','Bir kadr — bir tasodif.','Bir kadr — hech qachon yo‘qolmaydigan xotira.'],final:'Keyingi kadr hali suratga olinmagan. Eng zo‘ri oldinda.'},
 {slug:'apology-rain',group:'APOLOGY',name:'After Rain',ritual:'rain',tone:'rain',eyebrow:'YOMG‘IRDAN KEYIN',intro:'Ba’zan to‘g‘ri gapni ko‘rish uchun oynani tozalash kerak.',instruction:'Oynani artib oching',messages:['Men noto‘g‘ri qildim.','Bahona qidirmayman.','Faqat tushunishingni va eshitishingni istayman.'],final:'Agar imkon bersang, men bu safar gap bilan emas, harakat bilan tuzataman.'},
 {slug:'apology-ink',group:'APOLOGY',name:'Ink of Regret',ritual:'ink',tone:'ink',eyebrow:'YOZILMAY QOLGAN GAP',intro:'Bir tomchi siyoh ichida aytilmagan uzr bor.',instruction:'Siyoh tomchisiga teging',messages:['Avval xatoimni tan olaman.','Keyin seni tinglayman.','Va faqat keyin uzr so‘rayman.'],final:'Kechir deb talab qilmayman. Lekin chin dildan uzr so‘rayman.'},
 {slug:'apology-quiet',group:'APOLOGY',name:'Quiet Room',ritual:'lamp',tone:'quiet',eyebrow:'JIM XONA',intro:'Ba’zi so‘zlar faqat jimlikdan keyin eshitiladi.',instruction:'Chiroqni yoqing',messages:['Men gapirishdan oldin o‘yladim.','Nima og‘ritganini tushunishga harakat qildim.','Seni yo‘qotishdan ko‘ra, egoimni qo‘yib yuborishni tanlayman.'],final:'Men shu yerdaman. Gaplashishga tayyor bo‘lganingda, seni tinglayman.'},
 {slug:'proposal-pearl',group:'PROPOSAL',name:'Pearl Promise',ritual:'ring',tone:'proposal',eyebrow:'BIR SAVOL',intro:'Bu quti ichida uzukdan kattaroq narsa bor.',instruction:'Qutini ushlab oching',messages:['Bizning kechamiz.','Bizning uyimiz.','Bizning kelajagimiz.'],final:'Hayotimning keyingi barcha boblarini men bilan yozasanmi?'},
 {slug:'proposal-cinema',group:'PROPOSAL',name:'Cinema Proposal',ritual:'cinema',tone:'cinema',eyebrow:'BIZNING FILM',intro:'Bugungi namoyishda faqat bitta film bor.',instruction:'Proyektorni yoqing',messages:['1-akt: seni uchratdim.','2-akt: seni sevib qoldim.','3-akt: qolganini birga yozishni istayman.'],final:'Bu filmning davomiga “ha” deysanmi?'},
 {slug:'proposal-sky',group:'PROPOSAL',name:'Sky Promise',ritual:'sky',tone:'sky',eyebrow:'OSMONDA BITTA SAVOL',intro:'Tong otishidan oldin osmon bitta sirni saqlaydi.',instruction:'Yulduzlarni uyg‘oting',messages:['Bir yulduz — bugun uchun.','Bir yulduz — ertaga uchun.','Bir yulduz — butun umr uchun.'],final:'Har tongni yoningda kutib olishimga rozimisan?'}
];

export const EXPERIENCE_MAP=Object.fromEntries(EXPERIENCES.map(x=>[x.slug,x]));

export function selectedSlug(){
 const q=new URLSearchParams(location.search);
 return q.get('template')||'gallery';
}
