import { useEffect, useMemo, useRef, useState } from 'react';
import { readUrlContent } from '../../system/contentModel.js';
import { ExperienceSoundscape, ExperienceVideo, useExperienceMedia } from '../media/ExperienceMedia.jsx';
import './afterRainReborn.css';

const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const FALLBACKS=['https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=1200&q=80'];
function pulse(strong=false){try{navigator.vibrate?.(strong?[8,18,12]:[4])}catch{}}

function Rain({slow=false}){const ref=useRef(null);useEffect(()=>{const c=ref.current,ctx=c?.getContext('2d');if(!ctx)return;let raf=0,dead=false;const drops=Array.from({length:slow?28:96},()=>({x:Math.random(),y:Math.random(),s:.003+Math.random()*.006,l:18+Math.random()*48,a:.08+Math.random()*.28}));const resize=()=>{const d=Math.min(devicePixelRatio||1,1.4);c.width=c.clientWidth*d;c.height=c.clientHeight*d;ctx.setTransform(d,0,0,d,0,0)};resize();const ro=new ResizeObserver(resize);ro.observe(c);const draw=()=>{if(dead)return;const w=c.clientWidth,h=c.clientHeight;ctx.clearRect(0,0,w,h);for(const p of drops){p.y+=p.s*(slow?.18:1);if(p.y>1.1){p.y=-.1;p.x=Math.random()}ctx.strokeStyle=`rgba(214,229,238,${p.a})`;ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(p.x*w,p.y*h);ctx.lineTo(p.x*w-3,p.y*h+p.l);ctx.stroke()}raf=requestAnimationFrame(draw)};draw();return()=>{dead=true;cancelAnimationFrame(raf);ro.disconnect()}},[slow]);return <canvas ref={ref} className="arr-rain" aria-hidden="true"/>}

function Wipe({onProgress,onDone}){const ref=useRef(null),down=useRef(false),cells=useRef(new Set()),done=useRef(false),last=useRef(null);useEffect(()=>{const c=ref.current,ctx=c?.getContext('2d');if(!ctx)return;const paint=()=>{const d=Math.min(devicePixelRatio||1,1.4),w=c.clientWidth,h=c.clientHeight;c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0);const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'rgba(220,228,231,.86)');g.addColorStop(.5,'rgba(173,187,194,.76)');g.addColorStop(1,'rgba(225,230,232,.84)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h)};paint();const ro=new ResizeObserver(paint);ro.observe(c);return()=>ro.disconnect()},[]);const point=e=>{const r=ref.current.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};const erase=(x,y)=>{if(done.current)return;const c=ref.current,ctx=c.getContext('2d'),r=Math.max(38,Math.min(c.clientWidth,c.clientHeight)*.09);ctx.save();ctx.globalCompositeOperation='destination-out';const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,'rgba(0,0,0,.95)');g.addColorStop(.75,'rgba(0,0,0,.76)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();if(last.current){ctx.lineWidth=r*1.15;ctx.lineCap='round';ctx.strokeStyle='rgba(0,0,0,.72)';ctx.beginPath();ctx.moveTo(last.current.x,last.current.y);ctx.lineTo(x,y);ctx.stroke()}ctx.restore();last.current={x,y};cells.current.add(Math.floor(x/(c.clientWidth/8))+':'+Math.floor(y/(c.clientHeight/12)));const p=clamp(cells.current.size/38,0,1);onProgress(p);if(p>=1){done.current=true;pulse(true);onDone()}};return <canvas ref={ref} className="arr-fog" role="button" tabIndex={0} aria-label="Oynani barmoq bilan artib xotiralarni oching" onPointerDown={e=>{down.current=true;last.current=null;e.currentTarget.setPointerCapture?.(e.pointerId);const p=point(e);erase(p.x,p.y)}} onPointerMove={e=>{if(!down.current)return;const p=point(e);erase(p.x,p.y)}} onPointerUp={()=>{down.current=false;last.current=null}} onPointerCancel={()=>{down.current=false;last.current=null}} onKeyDown={e=>{if((e.key==='Enter'||e.key===' ')&&!done.current){e.preventDefault();onProgress(1);done.current=true;onDone()}}}/>}

export function AfterRainReborn({content:contentProp=null,media={},embedded=false}){
 const content=useMemo(()=>contentProp||readUrlContent('apology-rain'),[contentProp]);const assets=useExperienceMedia(media);const photos=assets.photos.length?assets.photos:FALLBACKS;const [phase,setPhase]=useState('storm');const [p,setP]=useState(0);const [memory,setMemory]=useState(0);
 const complete=()=>{setPhase('still');setTimeout(()=>{setPhase('memories');setMemory(1)},900)};const next=()=>{const n=Math.min(3,memory+1);setMemory(n);pulse();if(n===3)setTimeout(()=>setPhase(assets.video?'confession':'finale'),650)};
 return <main className={'after-rain-reborn '+(embedded?'is-embedded ':'')+'phase-'+phase}>
  <ExperienceSoundscape preset={content.musicPreset||'Nocturne'} customUrl={assets.music} startAt={content.musicStart||0}/><div className="arr-city"/><Rain slow={phase!=='storm'&&phase!=='wipe'}/><div className="arr-grain"/><div className="arr-vignette"/>
  <header className="arr-chrome"><a href="?">emora<span>.</span></a><small>AFTER RAIN · WINDOW OF TRUTH</small><b>{phase==='storm'?'00':phase==='wipe'?'01':phase==='still'?'02':phase==='memories'?'03':'04'}</b></header>
  <section className="arr-stage arr-storm"><article><p>THE GLASS REMEMBERS EVERYTHING</p><h1>{content.message||'Ba’zi gaplar yomg‘ir tinmaguncha ko‘rinmaydi.'}</h1><em>{content.recipient}</em></article><div className="arr-progress"><i style={{width:(p*100)+'%'}}/><span>{Math.round(p*100)}%</span></div><Wipe onProgress={v=>{setP(v);if(v>.02&&phase==='storm')setPhase('wipe')}} onDone={complete}/></section>
  <section className="arr-stage arr-still"><p>YOMG‘IR TINDI.</p><span>Bir lahza jimlik.</span></section>
  <section className="arr-stage arr-memories"><div className="arr-memory-copy"><p>03 · WHAT WAS BEHIND THE GLASS</p><h2>Uchta xotira. Uchta rost gap.</h2></div><div className="arr-photos">{photos.slice(0,3).map((src,i)=><figure key={i} className={i<memory?'show':''} style={{'--i':i}}><img src={src} alt=""/><figcaption>{content.captions?.[i]||['Seni yo‘qotishni istamayman.','Buni yengil qabul qilmayman.','Yaxshiroq qilishni xohlayman.'][i]}</figcaption></figure>)}</div><button onClick={next}>{memory<3?'Keyingi tomchini ochish':'Davom etish'} →</button></section>
  <section className="arr-stage arr-confession"><div className="arr-video"><ExperienceVideo src={assets.video} poster={photos[2]} title="Rain confession" autoReveal onEnded={()=>setPhase('finale')}/></div><button onClick={()=>setPhase('finale')}>Tongga o‘tish →</button></section>
  <section className="arr-stage arr-finale"><div className="arr-sun"/><article><p>AFTER THE RAIN</p><h2>{content.final||'Kechir deb talab qilmayman. Faqat bu safar harakat bilan to‘g‘rilashga ruxsat ber.'}</h2><em>{content.recipient}</em><button onClick={()=>location.reload()}>Boshidan ↺</button></article></section>
 </main>
}
