import { useEffect, useMemo, useRef, useState } from 'react';
import { readUrlContent } from '../../system/contentModel.js';
import { ExperienceSoundscape, ExperienceVideo, useExperienceMedia } from '../media/ExperienceMedia.jsx';
import './afterRainReborn.css';
import './afterRainFlagship.css';

const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const FALLBACKS=['https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=1200&q=80'];
function pulse(strong=false){try{navigator.vibrate?.(strong?[8,18,12]:[4])}catch{}}

function Rain({slow=false}){const ref=useRef(null);useEffect(()=>{const c=ref.current,ctx=c?.getContext('2d');if(!ctx)return;let raf=0,dead=false;const drops=Array.from({length:slow?30:110},()=>({x:Math.random(),y:Math.random(),s:.003+Math.random()*.006,l:18+Math.random()*52,a:.07+Math.random()*.3}));const resize=()=>{const d=Math.min(devicePixelRatio||1,1.4);c.width=c.clientWidth*d;c.height=c.clientHeight*d;ctx.setTransform(d,0,0,d,0,0)};resize();const ro=new ResizeObserver(resize);ro.observe(c);const draw=()=>{if(dead)return;const w=c.clientWidth,h=c.clientHeight;ctx.clearRect(0,0,w,h);for(const p of drops){p.y+=p.s*(slow?.2:1);if(p.y>1.1){p.y=-.1;p.x=Math.random()}ctx.strokeStyle=`rgba(214,229,238,${p.a})`;ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(p.x*w,p.y*h);ctx.lineTo(p.x*w-3,p.y*h+p.l);ctx.stroke()}raf=requestAnimationFrame(draw)};draw();return()=>{dead=true;cancelAnimationFrame(raf);ro.disconnect()}},[slow]);return <canvas ref={ref} className="arr-rain" aria-hidden="true"/>}

function Wipe({onProgress,onDone}){const ref=useRef(null),down=useRef(false),cells=useRef(new Set()),done=useRef(false),last=useRef(null);useEffect(()=>{const c=ref.current,ctx=c?.getContext('2d');if(!ctx)return;const paint=()=>{const d=Math.min(devicePixelRatio||1,1.4),w=c.clientWidth,h=c.clientHeight;c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0);const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'rgba(220,228,231,.88)');g.addColorStop(.5,'rgba(173,187,194,.8)');g.addColorStop(1,'rgba(225,230,232,.86)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h)};paint();const ro=new ResizeObserver(paint);ro.observe(c);return()=>ro.disconnect()},[]);const point=e=>{const r=ref.current.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};const erase=(x,y)=>{if(done.current)return;const c=ref.current,ctx=c.getContext('2d'),r=Math.max(40,Math.min(c.clientWidth,c.clientHeight)*.095);ctx.save();ctx.globalCompositeOperation='destination-out';const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,'rgba(0,0,0,1)');g.addColorStop(.75,'rgba(0,0,0,.78)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();if(last.current){ctx.lineWidth=r*1.18;ctx.lineCap='round';ctx.strokeStyle='rgba(0,0,0,.74)';ctx.beginPath();ctx.moveTo(last.current.x,last.current.y);ctx.lineTo(x,y);ctx.stroke()}ctx.restore();last.current={x,y};cells.current.add(Math.floor(x/(c.clientWidth/8))+':'+Math.floor(y/(c.clientHeight/12)));const p=clamp(cells.current.size/38,0,1);onProgress(p);if(p>=1){done.current=true;pulse(true);onDone()}};return <canvas ref={ref} className="arr-fog" role="button" tabIndex={0} aria-label="Oynani barmoq bilan artib xotiralarni oching" onPointerDown={e=>{down.current=true;last.current=null;e.currentTarget.setPointerCapture?.(e.pointerId);const p=point(e);erase(p.x,p.y)}} onPointerMove={e=>{if(!down.current)return;const p=point(e);erase(p.x,p.y)}} onPointerUp={()=>{down.current=false;last.current=null}} onPointerCancel={()=>{down.current=false;last.current=null}} onKeyDown={e=>{if((e.key==='Enter'||e.key===' ')&&!done.current){e.preventDefault();onProgress(1);done.current=true;onDone()}}}/>}

function TraceGlass({onDone}){const ref=useRef(null),down=useRef(false),last=useRef(null),length=useRef(0),done=useRef(false);useEffect(()=>{const c=ref.current,ctx=c?.getContext('2d');if(!ctx)return;const resize=()=>{const d=Math.min(devicePixelRatio||1,1.5);c.width=c.clientWidth*d;c.height=c.clientHeight*d;ctx.setTransform(d,0,0,d,0,0);ctx.lineCap='round';ctx.lineJoin='round'};resize();const ro=new ResizeObserver(resize);ro.observe(c);return()=>ro.disconnect()},[]);const point=e=>{const r=ref.current.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};const move=e=>{if(!down.current||done.current)return;const p=point(e),ctx=ref.current.getContext('2d');if(last.current){const dx=p.x-last.current.x,dy=p.y-last.current.y;length.current+=Math.hypot(dx,dy);ctx.strokeStyle='rgba(230,248,252,.92)';ctx.shadowColor='rgba(164,225,246,.8)';ctx.shadowBlur=18;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(last.current.x,last.current.y);ctx.lineTo(p.x,p.y);ctx.stroke()}last.current=p;if(length.current>420){done.current=true;down.current=false;pulse(true);setTimeout(onDone,260)}};return <canvas ref={ref} className="arr2-trace" role="button" tabIndex={0} aria-label="Bug‘langan oynaga barmoq bilan belgi chizing" onPointerDown={e=>{down.current=true;last.current=point(e);e.currentTarget.setPointerCapture?.(e.pointerId)}} onPointerMove={move} onPointerUp={()=>{down.current=false;last.current=null}} onPointerCancel={()=>{down.current=false;last.current=null}} onKeyDown={e=>{if((e.key==='Enter'||e.key===' ')&&!done.current){e.preventDefault();done.current=true;onDone()}}}/>}

export function AfterRainReborn({content:contentProp=null,media={},embedded=false}){
 const content=useMemo(()=>contentProp||readUrlContent('apology-rain'),[contentProp]);const assets=useExperienceMedia(media);const photos=assets.photos.length?assets.photos:FALLBACKS;const [phase,setPhase]=useState('storm');const [p,setP]=useState(0);
 const wiped=()=>{setPhase('still');setTimeout(()=>setPhase('drops'),720)};
 const traced=()=>{setPhase('rain-stop');setTimeout(()=>setPhase(assets.video?'confession':'sunrise'),900)};
 return <main className={'after-rain-reborn arr2 '+(embedded?'is-embedded ':'')+'phase-'+phase}>
  <ExperienceSoundscape preset={content.musicPreset||'Nocturne'} customUrl={assets.music} startAt={content.musicStart||0}/><div className="arr-city"/><Rain slow={!['storm','wipe'].includes(phase)}/><div className="arr2-reflection"/><div className="arr-grain"/><div className="arr-vignette"/>
  <header className="arr-chrome"><a href="?">emora<span>.</span></a><small>AFTER RAIN · GLASS CONFESSION</small><b>{phase==='storm'?'00':phase==='wipe'?'01':phase==='still'?'·':phase==='drops'?'02':phase==='trace'?'03':phase==='confession'?'04':'05'}</b></header>
  <section className="arr-stage arr-storm"><article><p>THE GLASS REMEMBERS EVERYTHING</p><h1>{content.message||'Ba’zi gaplar yomg‘ir tinmaguncha ko‘rinmaydi.'}</h1><em>{content.recipient}</em></article><div className="arr-progress"><i style={{width:(p*100)+'%'}}/><span>{Math.round(p*100)}%</span></div><Wipe onProgress={v=>{setP(v);if(v>.02&&phase==='storm')setPhase('wipe')}} onDone={wiped}/></section>
  <section className="arr-stage arr-still"><p>…</p><span>Bir lahza jimlik.</span></section>
  <section className="arr-stage arr2-drops"><div className="arr2-copy"><p>WHAT THE GLASS KEPT</p><h2>Uchta xotira. Bitta rost gap.</h2></div><div className="arr2-droplets">{photos.slice(0,3).map((src,i)=><figure key={i} style={{'--i':i}}><div><img src={src} alt=""/><i/></div><figcaption>{content.captions?.[i]||['Seni yo‘qotishni istamayman.','Buni yengil qabul qilmayman.','Yaxshiroq qilishni xohlayman.'][i]}</figcaption></figure>)}</div><button onClick={()=>setPhase('trace')}>Oynaga qaytish →</button></section>
  <section className="arr-stage arr2-trace-stage"><div className="arr2-trace-copy"><p>DON’T TAP · LEAVE A MARK</p><h2>Oynaga bir belgi chiz.</h2><span>Yomg‘ir shu gesture’ni kutyapti.</span></div><TraceGlass onDone={traced}/></section>
  <section className="arr-stage arr2-rain-stop"><span>YOMG‘IR TO‘XTADI.</span><i/></section>
  <section className="arr-stage arr-confession"><div className="arr2-video-glass"><ExperienceVideo src={assets.video} poster={photos[2]} title="Rain confession" autoReveal onEnded={()=>setPhase('sunrise')}/></div><button onClick={()=>setPhase('sunrise')}>Tongga o‘tish →</button></section>
  <section className="arr-stage arr-finale arr2-sunrise"><div className="arr-sun"/><div className="arr2-light-rays"><i/><i/><i/></div><article><p>AFTER THE RAIN</p><h2>{content.final||'Kechir deb talab qilmayman. Faqat bu safar harakat bilan to‘g‘rilashga ruxsat ber.'}</h2><em>{content.recipient}</em><button onClick={()=>location.reload()}>Boshidan ↺</button></article></section>
 </main>
}
