import {
  EXPERIENCE_ARCHETYPES as A,
  NAVIGATION_MODES as N,
  PRODUCT_CAPABILITIES as C,
} from './archetypes.js';

const commonInvite=[C.GUEST_GREETING,C.SHARE,C.VIEW_EVENTS];

export const TEMPLATE_MANIFEST = Object.freeze([
  {
    id:'love-rose',dbSlug:'love-rose-theatre',name:'Rose Theatre',category:'love',releaseStatus:'concept',
    archetype:A.RITUAL_OBJECT,navigation:N.RITUAL,
    metaphor:'velvet theatre',primaryMedia:'photo',
    signatureMoment:'The velvet curtain opens into a living theatre and the recipient reveal.',
    gestures:['drag-curtain','pluck-petal'],
    capabilities:[...commonInvite,C.PHOTOS,C.MUSIC,C.SAVE,C.RESPONSE],
    assets:{required:['curtain-art','recipient-photo'],optional:['petal-atlas','ambient-audio']},
    finale:'petal-photo-reveal',engine:['gsap','pixi-optional'],
    performance:{maxDpr:1.75,heavyLazyLoad:true},
  },
  {
    id:'love-pearl',dbSlug:'love-pearl-linen',name:'Pearl Linen',category:'love',releaseStatus:'review',
    archetype:A.RITUAL_OBJECT,navigation:N.RITUAL,
    metaphor:'handwritten private letter',primaryMedia:'paper',
    signatureMoment:'The seal fractures, the same letter slowly reveals ink and memories, then one final pearl hold dissolves the paper world into a portrait.',
    gestures:['hold-seal','drag-polaroid','hold-final-pearl'],
    capabilities:[...commonInvite,C.PHOTOS,C.PORTRAIT,C.MUSIC,C.SAVE,C.RESPONSE,C.WORD_LOCK],
    assets:{required:['envelope-art','wax-seal','paper-texture'],optional:['portrait-photo','memory-photos','custom-music']},
    finale:'particle-portrait',engine:['gsap','pixi'],
    performance:{maxDpr:1.75,heavyLazyLoad:true},
  },
  {
    id:'love-galaxy',dbSlug:'love-galaxy-confession',name:'Galaxy Confession',category:'love',releaseStatus:'concept',
    archetype:A.LIVING_WORLD,navigation:N.WORLD,
    metaphor:'interactive galaxy of personal words',primaryMedia:'webgl-world',
    signatureMoment:'The manipulable galaxy collapses into the recipient portrait.',
    gestures:['drag-galaxy','discover-stars','hold-collapse'],
    capabilities:[...commonInvite,C.PORTRAIT,C.MUSIC,C.SAVE,C.RESPONSE],
    assets:{required:['portrait-photo'],optional:['star-sprites','custom-music']},
    finale:'galaxy-to-portrait',engine:['pixi','gsap'],
    performance:{maxDpr:1.5,heavyLazyLoad:true},
  },
  {
    id:'wedding-silk',dbSlug:'wedding-silk-heritage',name:'Silk Heritage',category:'wedding',releaseStatus:'concept',
    archetype:A.EDITORIAL_STORY,navigation:N.PAGINATED,
    metaphor:'embroidered silk invitation',primaryMedia:'textile-editorial',
    signatureMoment:'A gold thread finishes the textile composition and reveals the couple and ceremony.',
    gestures:['pull-silk'],
    capabilities:[...commonInvite,C.RSVP,C.MAP,C.CALENDAR,C.MUSIC,C.PHOTOS,C.GUEST_LINKS],
    assets:{required:['silk-texture','embroidery-art'],optional:['couple-photo','music']},
    finale:'embroidered-invitation',engine:['gsap','svg'],
    performance:{maxDpr:2,heavyLazyLoad:false},
  },
  {
    id:'wedding-garden',dbSlug:'wedding-night-garden',name:'Night Garden',category:'wedding',releaseStatus:'concept',
    archetype:A.LIVING_WORLD,navigation:N.WORLD,
    metaphor:'living night garden',primaryMedia:'interactive-world',
    signatureMoment:'Lantern light and fireflies gather into the couple names and invitation.',
    gestures:['light-lanterns','open-garden'],
    capabilities:[...commonInvite,C.RSVP,C.MAP,C.CALENDAR,C.MUSIC,C.PHOTOS,C.GUEST_LINKS],
    assets:{required:['garden-art','lantern-art'],optional:['flower-atlas','ambient-audio']},
    finale:'firefly-name-bloom',engine:['pixi','gsap'],
    performance:{maxDpr:1.5,heavyLazyLoad:true},
  },
  {
    id:'wedding-naqsh',dbSlug:'wedding-heritage-naqsh',name:'Heritage Naqsh',category:'wedding',releaseStatus:'concept',
    archetype:A.EDITORIAL_STORY,navigation:N.PAGINATED,
    metaphor:'suzani-inspired geometric invitation',primaryMedia:'ornamental-editorial',
    signatureMoment:'The final geometric path locks into place and the full invitation appears inside the completed naqsh.',
    gestures:['trace-pattern','rotate-medallion'],
    capabilities:[...commonInvite,C.RSVP,C.MAP,C.CALENDAR,C.MUSIC,C.GUEST_LINKS],
    assets:{required:['naqsh-vector-set'],optional:['paper-texture','music']},
    finale:'completed-naqsh-invite',engine:['svg','gsap'],
    performance:{maxDpr:2,heavyLazyLoad:false},
  },
  {
    id:'birthday-aurora',dbSlug:'birthday-aurora-paper',name:'Aurora Paper',category:'birthday',releaseStatus:'concept',
    archetype:A.RITUAL_OBJECT,navigation:N.RITUAL,
    metaphor:'layered paper gift',primaryMedia:'paper-object',
    signatureMoment:'The final paper layer tears open and aurora light escapes into the whole screen.',
    gestures:['untie-ribbon','tear-paper'],
    capabilities:[...commonInvite,C.PHOTOS,C.MUSIC,C.SAVE,C.RESPONSE],
    assets:{required:['paper-layers','ribbon-art'],optional:['memory-photos','music']},
    finale:'aurora-release',engine:['rive-or-svg','gsap','pixi-optional'],
    performance:{maxDpr:1.75,heavyLazyLoad:true},
  },
  {
    id:'birthday-balloon',dbSlug:'birthday-balloon-dream',name:'Balloon Dream',category:'birthday',releaseStatus:'concept',
    archetype:A.LIVING_WORLD,navigation:N.WORLD,
    metaphor:'room of memory balloons',primaryMedia:'interactive-world',
    signatureMoment:'The final balloon bursts into a sky of memories and the recipient message.',
    gestures:['release-balloons','hold-pop'],
    capabilities:[...commonInvite,C.PHOTOS,C.MUSIC,C.SAVE,C.RESPONSE],
    assets:{required:['balloon-art'],optional:['memory-photos','confetti-atlas','music']},
    finale:'balloon-sky-message',engine:['pixi','gsap'],
    performance:{maxDpr:1.5,heavyLazyLoad:true},
  },
  {
    id:'birthday-memory',dbSlug:'birthday-memory-reel',name:'Memory Reel',category:'birthday',releaseStatus:'concept',
    archetype:A.CINEMATIC_MEMORY,navigation:N.TIMELINE,
    metaphor:'film reel of memories',primaryMedia:'photos-video',
    signatureMoment:'The chosen film frame burns through into the next-chapter birthday message.',
    gestures:['spin-reel','scrub-film','hold-frame'],
    capabilities:[...commonInvite,C.PHOTOS,C.MUSIC,C.SAVE,C.RESPONSE],
    assets:{required:['memory-photos'],optional:['film-grain','projector-audio','music']},
    finale:'film-burn-next-chapter',engine:['gsap','canvas-optional'],
    performance:{maxDpr:2,heavyLazyLoad:false},
  },
  {
    id:'apology-rain',dbSlug:'apology-after-rain',name:'After Rain',category:'apology',releaseStatus:'concept',
    archetype:A.ATMOSPHERIC_MINIMAL,navigation:N.RITUAL,
    metaphor:'rain-covered window',primaryMedia:'atmosphere',
    signatureMoment:'The final wipe clears the message as the rain stops and natural light returns.',
    gestures:['wipe-glass'],
    capabilities:[...commonInvite,C.PHOTOS,C.MUSIC,C.RESPONSE,C.SAVE],
    assets:{required:['rain-window'],optional:['photo','rain-audio']},
    finale:'rain-stop-light',engine:['pixi-or-canvas','gsap'],
    performance:{maxDpr:1.5,heavyLazyLoad:true},
  },
  {
    id:'apology-ink',dbSlug:'apology-ink-of-regret',name:'Ink of Regret',category:'apology',releaseStatus:'concept',
    archetype:A.RITUAL_OBJECT,navigation:N.RITUAL,
    metaphor:'ink spreading through paper',primaryMedia:'paper-fluid',
    signatureMoment:'Ink consumes the page, then retreats and leaves the apology in clean negative space.',
    gestures:['touch-ink','drag-nib'],
    capabilities:[...commonInvite,C.MUSIC,C.RESPONSE,C.SAVE],
    assets:{required:['paper-texture','nib-art'],optional:['ink-mask','music']},
    finale:'ink-negative-space',engine:['pixi-or-canvas','gsap'],
    performance:{maxDpr:1.5,heavyLazyLoad:true},
  },
  {
    id:'apology-quiet',dbSlug:'apology-quiet-room',name:'Quiet Room',category:'apology',releaseStatus:'concept',
    archetype:A.ATMOSPHERIC_MINIMAL,navigation:N.SINGLE,
    metaphor:'dark room and one lamp',primaryMedia:'light-atmosphere',
    signatureMoment:'One pull of the lamp chain reveals the entire intimate apology composition.',
    gestures:['pull-lamp'],
    capabilities:[...commonInvite,C.MUSIC,C.RESPONSE,C.SAVE],
    assets:{required:['room-art','lamp-art'],optional:['room-tone']},
    finale:'warm-room-reveal',engine:['rive-or-svg','gsap'],
    performance:{maxDpr:2,heavyLazyLoad:false},
  },
  {
    id:'proposal-pearl',dbSlug:'proposal-pearl-promise',name:'Pearl Promise',category:'proposal',releaseStatus:'concept',
    archetype:A.RITUAL_OBJECT,navigation:N.RITUAL,
    metaphor:'ring box and engraved promise',primaryMedia:'hero-object',
    signatureMoment:'Rotating the opened ring reveals a hidden engraving immediately before the proposal question.',
    gestures:['hold-box','rotate-ring'],
    capabilities:[...commonInvite,C.PHOTOS,C.MUSIC,C.RESPONSE,C.SAVE,C.OPEN_TIMER],
    assets:{required:['ring-box','ring-model-or-rive'],optional:['memory-photos','music']},
    finale:'engraving-to-question',engine:['spline-or-three','gsap'],
    performance:{maxDpr:1.5,heavyLazyLoad:true},
  },
  {
    id:'proposal-cinema',dbSlug:'proposal-cinema',name:'Cinema Proposal',category:'proposal',releaseStatus:'concept',
    archetype:A.CINEMATIC_MEMORY,navigation:N.TIMELINE,
    metaphor:'private cinema screening',primaryMedia:'photos-video',
    signatureMoment:'The film jams and burns through into the proposal question.',
    gestures:['start-projector','scrub-film'],
    capabilities:[...commonInvite,C.PHOTOS,C.MUSIC,C.RESPONSE,C.SAVE,C.OPEN_TIMER],
    assets:{required:['memory-photos','projector-art'],optional:['projector-audio','music']},
    finale:'film-burn-question',engine:['gsap','canvas-optional'],
    performance:{maxDpr:2,heavyLazyLoad:false},
  },
  {
    id:'proposal-sky',dbSlug:'proposal-sky-promise',name:'Sky Promise',category:'proposal',releaseStatus:'concept',
    archetype:A.LIVING_WORLD,navigation:N.WORLD,
    metaphor:'night sky becoming dawn',primaryMedia:'interactive-world',
    signatureMoment:'The manipulated night horizon becomes dawn and the proposal appears with sunrise.',
    gestures:['connect-stars','drag-horizon'],
    capabilities:[...commonInvite,C.MUSIC,C.RESPONSE,C.SAVE,C.OPEN_TIMER],
    assets:{required:['sky-gradient-system'],optional:['star-atlas','music']},
    finale:'dawn-question',engine:['pixi','gsap'],
    performance:{maxDpr:1.5,heavyLazyLoad:true},
  },
]);

export const TEMPLATE_BY_ID=Object.freeze(
  Object.fromEntries(TEMPLATE_MANIFEST.map(x=>[x.id,x]))
);

export const TEMPLATE_BY_DB_SLUG=Object.freeze(
  Object.fromEntries(TEMPLATE_MANIFEST.map(x=>[x.dbSlug,x]))
);

export function resolveTemplate(ref){
  return TEMPLATE_BY_ID[ref]||TEMPLATE_BY_DB_SLUG[ref]||null;
}
