import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm';
const SUPABASE_URL='https://mfbpjlwyjuycfqdokbfp.supabase.co';
const SUPABASE_KEY='sb_publishable_7ylqOOjt3k79ORiWlx1a4Q_NhMYJfS7';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('uz-UZ').format(Number(n||0))+' so‘m';const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
let loading=false;
function showLauncher(){const b=$('#v17-admin-mobile-btn');if(!b)return;b.style.display=matchMedia('(max-width:1050px)').matches?'block':'none'}
function hideLauncher(){const b=$('#v17-admin-mobile-btn');if(b)b.style.display='none'}
function wireLaunchers(){const navLink=$('.nav a[href="#dashboard"]');if(navLink&&!$('#v17-admin-btn')){navLink.id='v17-admin-btn';navLink.classList.add('v17-admin-nav-launcher');navLink.textContent='Dashboard';navLink.addEventListener('click',e=>{e.preventDefault();open()})}if(!$('#v17-admin-mobile-btn')){const b=document.createElement('button');b.id='v17-admin-mobile-btn';b.type='button';b.className='v17-admin-mobile-btn';b.textContent='Dashboard';b.setAttribute('aria-label','Owner dashboard');b.onclick=open;document.body.append(b);showLauncher()}}
function close(){const modal=$('#v17-admin-modal');if(modal)modal.classList.add('hidden');showLauncher()}
function build(){if(location.pathname.startsWith('/s/')||$('#v17-admin-modal'))return;wireLaunchers();const modal=document.createElement('div');modal.id='v17-admin-modal';modal.className='v17-admin-modal hidden';modal.innerHTML=`<section class="v17-admin-card" role="dialog" aria-modal="true" aria-labelledby="v17-admin-title"><header><div><small>EMORA OWNER</small><h2 id="v17-admin-title">Business dashboard</h2><p>Project, view, RSVP va payment holati — faqat sizning akkauntingiz uchun.</p></div><div class="v17-admin-actions"><button type="button" id="v17-admin-refresh">Yangilash</button><button type="button" id="v17-admin-close" aria-label="Yopish">×</button></div></header><div id="v17-admin-body"><div class="v17-admin-empty">Dashboard yuklanishga tayyor.</div></div></section>`;document.body.append(modal);$('#v17-admin-close').onclick=close;$('#v17-admin-refresh').onclick=load;modal.onclick=e=>{if(e.target===modal)close()}}
function summaryCard(value,label,detail=''){return `<article class="v17-kpi"><b>${esc(value)}</b><span>${esc(label)}</span>${detail?`<small>${esc(detail)}</small>`:''}</article>`}
async function open(){build();hideLauncher();$('#v17-admin-modal').classList.remove('hidden');await load()}
async function load(){if(loading)return;loading=true;const body=$('#v17-admin-body');if(!body){loading=false;return}body.innerHTML='<div class="v17-admin-empty">Ma’lumotlar yuklanmoqda…</div>';try{const {data:{user}}=await supabase.auth.getUser();if(!user){body.innerHTML='<div class="v17-admin-empty"><strong>Akkauntga kiring</strong><span>Dashboard faqat loyiha egasiga ko‘rinadi.</span><button type="button" id="v17-admin-login">Kirish</button></div>';$('#v17-admin-login').onclick=()=>{close();$('#accountBtn')?.click()};return}
 const [{data:projects,error:pe},{data:orders,error:oe}]=await Promise.all([supabase.from('projects').select('id,title,status,template_slug,slug,updated_at,published_at').order('updated_at',{ascending:false}).limit(50),supabase.from('payment_orders').select('id,project_id,status,provider,amount_uzs,created_at,paid_at').order('created_at',{ascending:false}).limit(100)]);if(pe)throw pe;if(oe)throw oe;
 const analytics=await Promise.all((projects||[]).map(async p=>{const {data,error}=await supabase.rpc('project_analytics',{p_project_id:p.id});return {project:p,a:error?{}:(data?.[0]||{})}}));
 const paid=(orders||[]).filter(x=>x.status==='paid'),published=(projects||[]).filter(x=>x.status==='published'),views=analytics.reduce((s,x)=>s+Number(x.a.total_views||0),0),yes=analytics.reduce((s,x)=>s+Number(x.a.yes_count||0),0),attendees=analytics.reduce((s,x)=>s+Number(x.a.attendees_total||0),0),revenue=paid.reduce((s,x)=>s+Number(x.amount_uzs||0),0);
 const kpis=`<div class="v17-kpis">${summaryCard(projects?.length||0,'PROJECT')}${summaryCard(published.length,'PUBLISHED')}${summaryCard(views,'VIEWS')}${summaryCard(money(revenue),'REVENUE',paid.length+' paid order')}${summaryCard(yes,'RSVP · HA',attendees+' attendee')}</div>`;
 const rows=analytics.length?analytics.map(({project:p,a})=>`<article class="v17-project"><div class="v17-project-main"><small>${esc(String(p.status||'draft').toUpperCase())} · ${esc(p.template_slug)}</small><strong>${esc(p.title||'Untitled')}</strong><span>${new Date(p.updated_at).toLocaleString('uz-UZ')}</span></div><div class="v17-project-metrics"><span><b>${Number(a.total_views||0)}</b>view</span><span><b>${Number(a.yes_count||0)}</b>ha</span><span><b>${Number(a.maybe_count||0)}</b>balki</span><span><b>${Number(a.no_count||0)}</b>yo‘q</span></div>${p.slug?`<a href="/s/${encodeURIComponent(p.slug)}" target="_blank" rel="noopener">Public link ↗</a>`:''}</article>`).join(''):'<div class="v17-admin-empty">Hali project yo‘q.</div>';
 const paymentRows=(orders||[]).slice(0,8).map(o=>`<tr><td>${esc((o.provider||'—').toUpperCase())}</td><td><span class="v17-pay-status" data-status="${esc(o.status)}">${esc(o.status)}</span></td><td>${money(o.amount_uzs)}</td><td>${new Date(o.paid_at||o.created_at).toLocaleString('uz-UZ')}</td></tr>`).join('')||'<tr><td colspan="4">Hali payment yo‘q.</td></tr>';
 body.innerHTML=`${kpis}<div class="v17-admin-grid"><section><div class="v17-section-head"><h3>Project performance</h3><span>${analytics.length} ta</span></div><div class="v17-project-list">${rows}</div></section><section><div class="v17-section-head"><h3>Payments</h3><span>oxirgi 8 ta</span></div><div class="v17-payment-table"><table><thead><tr><th>Provider</th><th>Status</th><th>Summa</th><th>Vaqt</th></tr></thead><tbody>${paymentRows}</tbody></table></div></section></div>`;
 }catch(e){body.innerHTML=`<div class="v17-admin-empty"><strong>Dashboard xatosi</strong><span>${esc(e.message||'Ma’lumot olinmadi')}</span></div>`}finally{loading=false}}
function boot(){if(location.pathname.startsWith('/s/'))return;build();showLauncher();window.__EMORA_V17_ADMIN__={version:17,ownerOnly:true,topLayerLauncher:false,positionedLauncher:true,metrics:['projects','published','views','rsvp','revenue','payments']}}
boot();
