import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import {randomBytes,timingSafeEqual} from 'node:crypto';
import {fileURLToPath} from 'node:url';
const ROOT=path.dirname(fileURLToPath(import.meta.url));
const PUBLIC=path.join(ROOT,'public');
const DATA=path.resolve(process.env.DATA_DIR||path.join(ROOT,'data'));
const PORT=Number(process.env.PORT||3000);
const ADMIN_KEY=process.env.EMORA_ADMIN_KEY||'';
const BOT_TOKEN=process.env.TELEGRAM_BOT_TOKEN||'';
const BOT_CHAT=process.env.TELEGRAM_CHAT_ID||'';
const DEMO_ONLY=process.env.EMORA_DEMO_ONLY==='1';
const PRESETS=new Set(['yulduz','sokin','quvonch','va-da']);
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webp':'image/webp','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.ogg':'audio/ogg','.mp3':'audio/mpeg','.mp4':'video/mp4','.webm':'video/webm','.m4a':'audio/mp4','.json':'application/json'};
const LIMITS={photo:8*1024*1024,video:64*1024*1024,audio:20*1024*1024};
const KINDS={photo:['image/jpeg','image/png','image/webp'],video:['video/mp4','video/webm'],audio:['audio/mpeg','audio/ogg','audio/mp4']};
const EXT={'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','video/mp4':'.mp4','video/webm':'.webm','audio/mpeg':'.mp3','audio/ogg':'.ogg','audio/mp4':'.m4a'};
const rate=new Map();
const idOk=id=>/^[a-f0-9]{24}$/.test(id);
const txt=(x,max=160)=>typeof x==='string'?x.trim().slice(0,max):'';
const fail=(status,message)=>Object.assign(new Error(message),{status});
function reply(res,status,obj){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(obj))}
function admin(req){if(ADMIN_KEY){const given=req.headers.authorization||'';if(given.length!==ADMIN_KEY.length+7||!given.startsWith('Bearer '))return false;const a=Buffer.from(given.slice(7)),b=Buffer.from(ADMIN_KEY);return a.length===b.length&&timingSafeEqual(a,b)}const remote=req.socket.remoteAddress||'';return process.env.NODE_ENV!=='production'&&['127.0.0.1','::1','::ffff:127.0.0.1'].includes(remote)}
async function body(req,max){const size=Number(req.headers['content-length']||0);if(size>max)throw fail(413,'Fayl hajmi cheklovdan oshdi');let total=0,chunks=[];for await(const part of req){total+=part.length;if(total>max)throw fail(413,'Fayl hajmi cheklovdan oshdi');chunks.push(part)}return Buffer.concat(chunks)}
function signature(b,type){if(b.length<12)return false;const magic=b.toString('ascii',0,12);if(type==='image/jpeg')return b[0]===0xff&&b[1]===0xd8&&b[2]===0xff;if(type==='image/png')return b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));if(type==='image/webp')return magic.startsWith('RIFF')&&magic.slice(8,12)==='WEBP';if(type==='video/mp4'||type==='audio/mp4')return magic.slice(4,8)==='ftyp';if(type==='video/webm')return b.subarray(0,4).equals(Buffer.from([26,69,223,163]));if(type==='audio/ogg')return magic.startsWith('OggS');if(type==='audio/mpeg')return magic.startsWith('ID3')||b[0]===0xff&&(b[1]&0xe0)===0xe0;return false}
function mediaPath(x){return typeof x==='string'&&/^\/media\/[a-f0-9]{24}\.(jpg|jpeg|png|webp|mp4|webm|mp3|ogg|m4a)$/.test(x)?x:''}
function validate(input){if(!input||typeof input!=='object')throw fail(400,'Hikoya ma’lumotlari noto‘g‘ri');const type=['birthday','apology','proposal'].includes(input.type)?input.type:null;if(!type)throw fail(400,'Yo‘nalishni tanlang');const variant=Number(input.variant);if(!Number.isInteger(variant)||variant<0||variant>4)throw fail(400,'Shablon noto‘g‘ri');const photos=Array.isArray(input.photos)?input.photos.slice(0,6).map(p=>({url:mediaPath(p.url),caption:txt(p.caption,120)})):[];if(photos.some(p=>!p.url))throw fail(400,'Rasm manzili noto‘g‘ri');const video=mediaPath(input.video);if(!video||!['.mp4','.webm'].some(x=>video.endsWith(x)))throw fail(400,'Video yuklang');if(!photos.length)throw fail(400,'Kamida bitta rasm yuklang');const preset=PRESETS.has(input.music)?input.music:'';const custom=mediaPath(input.music);if(!preset&&(!custom||!['.mp3','.ogg','.m4a'].some(x=>custom.endsWith(x))))throw fail(400,'Musiqani tanlang');const result={type,variant,recipient:txt(input.recipient,70),sender:txt(input.sender,70),nickname:txt(input.nickname,40),message:txt(input.message,600),wish:txt(input.wish,160),mistake:txt(input.mistake,180),repair:txt(input.repair,180),letter:txt(input.letter,900),photos,video,music:preset||custom,meetingOptions:Array.isArray(input.meetingOptions)?input.meetingOptions.map(x=>txt(x,80)).filter(Boolean).slice(0,4):[]};if(!result.recipient||!result.sender||!result.message)throw fail(400,'Ismlar va xabarni kiriting');if(type==='birthday'&&!result.nickname)throw fail(400,'Sirli laqabni kiriting');if(type==='apology'&&result.meetingOptions.length<3)throw fail(400,'Kamida uchta uchrashuv joyini kiriting');return result}
async function serve(res,base,relative){const target=path.resolve(base,'.'+relative);if(!target.startsWith(base+path.sep))throw fail(404,'Topilmadi');let st;try{st=await fs.stat(target)}catch{throw fail(404,'Topilmadi')}if(!st.isFile())throw fail(404,'Topilmadi');res.writeHead(200,{'Content-Type':MIME[path.extname(target)]||'application/octet-stream','Content-Length':st.size,'X-Content-Type-Options':'nosniff','Cache-Control':target.includes('/media/')?'public, max-age=31536000, immutable':'no-cache'});res.end(await fs.readFile(target))}
function shareLink(req,storyId,message){const origin=process.env.PUBLIC_ORIGIN||`http://localhost:${PORT}`;const url=new URL(`/s/${storyId}`,origin).href;return `https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(message)}`}
async function notifyTelegram(message){if(!BOT_TOKEN||!BOT_CHAT)return false;const r=await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:BOT_CHAT,text:message}),signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error('Telegram bot yubora olmadi');return true}
function throttle(req,id){const key=(req.socket.remoteAddress||'unknown')+':'+id,now=Date.now(),times=(rate.get(key)||[]).filter(t=>now-t<60000);if(times.length>=5)throw fail(429,'Bir daqiqada juda ko‘p javob yuborildi');times.push(now);rate.set(key,times);if(rate.size>2000)for(const [k,t] of rate)if(t[t.length-1]<now-60000)rate.delete(k)}
async function run(req,res){const url=new URL(req.url,'http://localhost');const pathname=decodeURIComponent(url.pathname);if(req.method==='GET'&&pathname==='/health')return reply(res,200,{ok:true});if(DEMO_ONLY&&req.method==='GET'&&pathname==='/'){res.writeHead(302,{Location:'/demo/','Cache-Control':'no-store'});return res.end()}if(DEMO_ONLY&&(req.method!=='GET'||pathname.startsWith('/api/')))throw fail(403,'Demo rejimida shaxsiy ma’lumotlar qabul qilinmaydi');if(req.method==='GET'&&pathname==='/api/config')return reply(res,200,{adminRequired:!!ADMIN_KEY,telegramAuto:!!BOT_TOKEN&&!!BOT_CHAT});
if(req.method==='POST'&&pathname==='/api/media'){if(!admin(req))throw fail(401,'Admin kaliti kerak');const kind=url.searchParams.get('kind'),type=(req.headers['content-type']||'').split(';')[0];if(!KINDS[kind]?.includes(type))throw fail(415,'Bu fayl turi qo‘llanmaydi');const file=await body(req,LIMITS[kind]);if(!signature(file,type))throw fail(415,'Fayl tarkibi noto‘g‘ri');const filename=randomBytes(12).toString('hex')+EXT[type];await fs.writeFile(path.join(DATA,'media',filename),file,{flag:'wx'});return reply(res,201,{url:'/media/'+filename,size:file.length})}
if(req.method==='POST'&&pathname==='/api/stories'){if(!admin(req))throw fail(401,'Admin kaliti kerak');const input=JSON.parse((await body(req,40000)).toString('utf8'));const story=validate(input),id=randomBytes(12).toString('hex');const saved={...story,id,createdAt:new Date().toISOString()};await fs.writeFile(path.join(DATA,'stories',id+'.json'),JSON.stringify(saved),{flag:'wx'});return reply(res,201,{id,url:'/s/'+id})}
const match=/^\/api\/stories\/([a-f0-9]{24})(?:\/(respond|responses))?$/.exec(pathname);if(match){const [,id,action]=match;let story;try{story=JSON.parse(await fs.readFile(path.join(DATA,'stories',id+'.json'),'utf8'))}catch{throw fail(404,'Hikoya topilmadi')}
 if(req.method==='GET'&&!action)return reply(res,200,story);
 if(req.method==='GET'&&action==='responses'){if(!admin(req))throw fail(401,'Admin kaliti kerak');let lines='';try{lines=await fs.readFile(path.join(DATA,'responses',id+'.jsonl'),'utf8')}catch{}return reply(res,200,{items:lines.trim()?lines.trim().split('\n').map(x=>JSON.parse(x)):[]})}
 if(req.method==='POST'&&action==='respond'){throttle(req,id);const input=JSON.parse((await body(req,4000)).toString('utf8'));const choice=input.choice;if(!['yes','no','later'].includes(choice))throw fail(400,'Javob noto‘g‘ri');let place='',date='',time='';if(story.type==='apology'&&choice==='yes'){place=txt(input.place,80);date=txt(input.date,10);time=txt(input.time,5);if(!story.meetingOptions.includes(place)||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(time)||Number.isNaN(new Date(`${date}T${time}:00`).getTime())||date<new Date().toISOString().slice(0,10))throw fail(400,'Uchrashuv joyi, kuni va soatini to‘g‘ri tanlang')}
 const record={choice,place,date,time,createdAt:new Date().toISOString()};await fs.appendFile(path.join(DATA,'responses',id+'.jsonl'),JSON.stringify(record)+'\n');const word=choice==='yes'?'Roziman':choice==='no'?'Rozi emasman':'Menga vaqt kerak';const msg=`EMORA · ${story.type==='apology'?'Uzrga javob':'Turmush taklifiga javob'}\n${story.recipient}: ${word}${place?`\nJoy: ${place}\nKun: ${date}\nSoat: ${time}`:''}\nHikoya: ${process.env.PUBLIC_ORIGIN||'http://localhost:'+PORT}/s/${id}`;let sent=false;try{sent=await notifyTelegram(msg)}catch(e){console.error('Telegram:',e.message)}return reply(res,200,{saved:true,telegramSent:sent,shareUrl:sent?'':shareLink(req,id,msg),message:sent?'Javob yuborildi':'Javob saqlandi. Telegram orqali yuborishni tasdiqlang.'})}
 }
if(req.method==='GET'&&pathname.startsWith('/media/'))return serve(res,path.join(DATA,'media'),pathname.slice(6));
if(req.method==='GET'&&(pathname==='/demo'||pathname==='/demo/'))return serve(res,PUBLIC,'/demo/index.html');
if(req.method==='GET'&&(/^\/s\/[a-f0-9]{24}$/.test(pathname)||pathname==='/'))return serve(res,PUBLIC,'/index.html');
if(req.method==='GET')return serve(res,PUBLIC,pathname);
throw fail(405,'Usul qo‘llanmaydi')}
await Promise.all(['media','stories','responses'].map(x=>fs.mkdir(path.join(DATA,x),{recursive:true})));
const server=http.createServer((req,res)=>{run(req,res).catch(e=>{console.error(e.status?`${e.status}: ${e.message}`:e);if(!res.headersSent)reply(res,e.status||500,{error:e.status?e.message:'Server xatosi'})})});
server.listen(PORT,()=>console.log(`EMORA: http://localhost:${PORT}`));
export {server,validate,signature};
