import { useMemo, useRef, useState } from 'react';
import { readUrlContent } from '../../system/contentModel.js';
import { ExperienceSoundscape, ExperienceVideo, useExperienceMedia } from '../media/ExperienceMedia.jsx';
import './heritageNaqshReborn.css';

const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const FALLBACKS=['https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1200&q=80'];
function pulse(strong=false){try{navigator.vibrate?.(strong?[9,20,12]:[4])}catch{}}
function fmt(v){if(!v)return {date:'Sana tez orada',time:''};const d=new Date(v);if(Number.isNaN(d.getTime()))return {date:v,time:''};return{date:new Intl.DateTimeFormat('uz-UZ',{day:'numeric',month:'long',year:'numeric'}).format(d),time:new Intl.DateTimeFormat('uz-UZ',{hour:'2-digit',minute:'2-digit'}).format(d)}}

function Trace({onDone}){const last=useRef(null),dist=useRef(0),done=useRef(false);const [p,setP]=useState(0);const down=e=>{last.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture?.(e.pointerId)};const finish=()=>{if(done.current)return;done.current=true;setP(1);pulse(true);setTimeout(onDone,360)};const move=e=>{if(!last.current||done.current)return;const dx=e.clientX-last.current.x,dy=e.clientY-last.current.y;dist.current+=Math.hypot(dx,dy);last.current={x:e.clientX,y:e.clientY};const n=clamp(dist.current/580,0,1);setP(n);if(n>.96)finish()};return <div className="hnr-trace" style={{'--dash':1-p}}><svg viewBox="0 0 800 800" aria-hidden="true"><g className="hnr-base"><circle cx="400" cy="400" r="292"/><circle cx="400" cy="400" r="222"/><rect x="240" y="240" width="320" height="320" transform="rotate(45 400 400)"/></g><path className="hnr-live" pathLength="1" d="M400 92 C438 196 520 218 625 175 C582 279 605 358 708 400 C605 442 582 521 625 625 C520 582 438 604 400 708 C362 604 280 582 175 625 C218 521 195 442 92 400 C195 358 218 279 175 175 C280 218 362 196 400 92Z"/></svg><button aria-label="Naqshni barmoq bilan chizing" onPointerDown={down} onPointerMove={move} onPointerUp={()=>last.current=null} onPointerCancel={()=>last.current=null} onKeyDown={e=>{if((e.key==='Enter'||e.key===' ')&&!e.repeat){e.preventDefault();finish()}}}><span>naqshni chizing</span><b>{Math.round(p*100)}%</b></button></div>}

export function HeritageNaqshReborn({content:contentProp=null,media={},embedded=false}){
 const content=useMemo(()=>contentProp||readUrlContent('wedding-naqsh'),[contentProp]);const assets=useExperienceMedia(media);const photos=assets.photos.length?assets.photos:FALLBACKS;const date=useMemo(()=>fmt(content.eventDate),[content.eventDate]);const [phase,setPhase]=useState('dot');const [med,setMed]=useState(0);
 const next=()=>{const n=Math.min(3,med+1);setMed(n);pulse();if(n===3)setTimeout(()=>setPhase(assets.video?'film':'finale'),650)};
 return <main className={'heritage-naqsh-reborn '+(embedded?'is-embedded ':'')+'phase-'+phase}>
  <ExperienceSoundscape preset={content.musicPreset||'Heritage'} customUrl={assets.music} startAt={content.musicStart||0}/><div className="hnr-paper"/><div className="hnr-grain"/><div className="hnr-vignette"/>
  <header className="hnr-chrome"><a href="?">emora<span>.</span></a><small>HERITAGE NAQSH · LIVING PATTERN</small><b>{phase==='dot'?'00':phase==='trace'?'01':phase==='medallions'?'02':phase==='film'?'03':'04'}</b></header>
  <section className="hnr-stage hnr-dot"><div className="hnr-seed"/><article><p>ONE DOT · ONE FAMILY PATTERN</p><h1>{content.message||'Har bir katta naqsh bitta nuqtadan boshlanadi.'}</h1><em>{content.guestGreeting||content.recipient}</em><button onClick={()=>setPhase('trace')}>Naqshni boshlash →</button></article></section>
  <section className="hnr-stage hnr-trace-stage"><div className="hnr-head"><p>01 · TRACE THE HERITAGE</p><h2>Yo‘lni qo‘ling bilan qur.</h2></div><Trace onDone={()=>setPhase('medallions')}/></section>
  <section className="hnr-stage hnr-medallions"><div className="hnr-head"><p>02 · THREE MEDALLIONS</p><h2>Naqsh ichida uchta xotira.</h2></div><div className="hnr-med-grid">{photos.slice(0,3).map((src,i)=><figure key={i} className={i<med?'open':''} style={{'--i':i}}><div><img src={src} alt=""/><i/></div><figcaption>{content.captions?.[i]||['Boshlanish.','Birga kulgan kun.','Yangi oilaning birinchi sahifasi.'][i]}</figcaption></figure>)}</div><button onClick={next}>{med<3?'Keyingi medalyonni ochish':'Markazni ochish'} →</button></section>
  <section className="hnr-stage hnr-film"><div className="hnr-film-medallion"><ExperienceVideo src={assets.video} poster={photos[1]} title="Wedding film" autoReveal onEnded={()=>setPhase('finale')}/><i/></div><button onClick={()=>setPhase('finale')}>Naqshni yakunlash →</button></section>
  <section className="hnr-stage hnr-finale"><div className="hnr-final-pattern"><i/><b/><span/></div><article><p>THE PATTERN IS COMPLETE</p><h2>{content.final||'Sizni hayotimizning eng muhim kuniga taklif qilamiz.'}</h2><em>{content.recipient}</em><div className="hnr-meta"><span><small>SANA</small><b>{date.date}</b><i>{date.time}</i></span><span><small>JOY</small><b>{content.venueName||'Toshkent'}</b><i>{content.venueAddress||''}</i></span></div><button onClick={()=>location.reload()}>Boshidan ↺</button></article></section>
 </main>
}
