import { useMemo, useRef, useState } from 'react';
import { readUrlContent } from '../../system/contentModel.js';
import { ExperienceSoundscape, ExperienceVideo, useExperienceMedia } from '../media/ExperienceMedia.jsx';
import './nightGardenReborn.css';

const FALLBACKS=['https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1200&q=80'];
function pulse(strong=false){try{navigator.vibrate?.(strong?[8,18,12]:[4])}catch{}}
function fmt(v){if(!v)return {date:'Sana tez orada',time:''};const d=new Date(v);if(Number.isNaN(d.getTime()))return {date:v,time:''};return{date:new Intl.DateTimeFormat('uz-UZ',{day:'numeric',month:'long',year:'numeric'}).format(d),time:new Intl.DateTimeFormat('uz-UZ',{hour:'2-digit',minute:'2-digit'}).format(d)}}
function Gate({onDone}){const start=useRef(null),done=useRef(false),[p,setP]=useState(0);const down=e=>{start.current=e.clientX;e.currentTarget.setPointerCapture?.(e.pointerId)};const move=e=>{if(start.current==null||done.current)return;const n=Math.max(0,Math.min(1,(e.clientX-start.current)/230));setP(n);if(n>.95){done.current=true;pulse(true);setTimeout(onDone,380)}};return <button className="ngr-gate-control" style={{'--p':p}} aria-label="Bog‘ darvozasini o‘ngga surib oching" onPointerDown={down} onPointerMove={move} onPointerUp={()=>start.current=null} onPointerCancel={()=>start.current=null}><i/><span>darvozani suring →</span></button>}

export function NightGardenReborn({content:contentProp=null,media={},embedded=false}){
 const content=useMemo(()=>contentProp||readUrlContent('wedding-garden'),[contentProp]);const assets=useExperienceMedia(media);const photos=assets.photos.length?assets.photos:FALLBACKS;const date=useMemo(()=>fmt(content.eventDate),[content.eventDate]);const [phase,setPhase]=useState('gate');const [lanterns,setLanterns]=useState([]);
 const light=i=>{if(lanterns.includes(i))return;const n=[...lanterns,i];setLanterns(n);pulse();if(n.length===3)setTimeout(()=>setPhase(assets.video?'pavilion':'finale'),800)};
 return <main className={'night-garden-reborn '+(embedded?'is-embedded ':'')+'phase-'+phase}>
  <ExperienceSoundscape preset={content.musicPreset||'Heritage'} customUrl={assets.music} startAt={content.musicStart||0}/><div className="ngr-world"><div className="ngr-sky"/><div className="ngr-moon"/><div className="ngr-path"/><div className="ngr-hedge left"/><div className="ngr-hedge right"/><div className="ngr-pavilion"/><div className="ngr-gate left"/><div className="ngr-gate right"/></div><div className="ngr-fireflies">{Array.from({length:32},(_,i)=><i key={i} style={{'--i':i}}/>)}</div><div className="ngr-grain"/><div className="ngr-vignette"/>
  <header className="ngr-chrome"><a href="?">emora<span>.</span></a><small>NIGHT GARDEN · MOON CEREMONY</small><b>{phase==='gate'?'00':phase==='lanterns'?'01':phase==='pavilion'?'02':'03'}</b></header>
  <section className="ngr-stage ngr-gate-stage"><article><p>THE GARDEN OPENS AFTER DARK</p><h1>{content.message||'Bu bog‘ bugun faqat bitta marosim uchun yoritiladi.'}</h1><em>{content.guestGreeting||content.recipient}</em></article><Gate onDone={()=>setPhase('lanterns')}/></section>
  <section className="ngr-stage ngr-lanterns"><div className="ngr-head"><p>01 · LIGHT THE PATH</p><h2>Uch chiroq. Uch xotira.</h2></div><div className="ngr-lantern-field">{[0,1,2].map(i=><button key={i} className={'ngr-lantern '+(lanterns.includes(i)?'lit':'')} style={{'--i':i}} aria-label={(i+1)+'-chiroqni yoqing'} onClick={()=>light(i)}><i/><b/><span/></button>)}</div><div className="ngr-memory-blooms">{photos.slice(0,3).map((src,i)=><figure key={i} className={lanterns.includes(i)?'show':''} style={{'--i':i}}><img src={src} alt=""/><figcaption>{content.captions?.[i]||['Bizning boshlanishimiz.','Birga kulgan kunimiz.','Yangi uyimiz tomon.'][i]}</figcaption></figure>)}</div></section>
  <section className="ngr-stage ngr-pavilion-stage"><div className="ngr-video"><ExperienceVideo src={assets.video} poster={photos[1]} title="Garden wedding film" autoReveal onEnded={()=>setPhase('finale')}/></div><p>PAVILION · PRIVATE FILM</p><button onClick={()=>setPhase('finale')}>Bog‘ni to‘liq yoqish →</button></section>
  <section className="ngr-stage ngr-finale"><div className="ngr-lights">{Array.from({length:24},(_,i)=><i key={i} style={{'--i':i}}/>)}</div><article><p>THE WHOLE GARDEN IS LIT</p><h2>{content.final||'Sizni hayotimizning eng go‘zal oqshomiga taklif qilamiz.'}</h2><em>{content.recipient}</em><div className="ngr-meta"><span><small>SANA</small><b>{date.date}</b><i>{date.time}</i></span><span><small>JOY</small><b>{content.venueName||'Toshkent'}</b><i>{content.venueAddress||''}</i></span></div><button onClick={()=>location.reload()}>Boshidan ↺</button></article></section>
 </main>
}
