create table if not exists public.payment_plans (
  slug text primary key,
  name text not null,
  amount_uzs integer not null check (amount_uzs > 0),
  is_active boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.payment_plans enable row level security;
insert into public.payment_plans(slug,name,amount_uzs,is_active,sort_order) values
 ('template','Template',49990,true,10),
 ('ai_lite','Template + AI Lite',69990,false,20),
 ('ai_custom','Full Custom AI',199990,false,30)
on conflict (slug) do update set name=excluded.name, amount_uzs=excluded.amount_uzs, is_active=excluded.is_active, sort_order=excluded.sort_order, updated_at=now();
drop policy if exists "payment plans public read" on public.payment_plans;
create policy "payment plans public read" on public.payment_plans for select to anon, authenticated using (true);
grant select on public.payment_plans to anon, authenticated;

create table if not exists public.payment_orders (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,
  provider text not null check (provider in ('click','payme')),
  plan_slug text not null references public.payment_plans(slug),
  amount_uzs integer not null check (amount_uzs > 0),
  amount_tiyin bigint not null check (amount_tiyin > 0),
  status text not null default 'pending' check (status in ('pending','paid','cancelled','failed','expired','refunded')),
  publish_slug text not null check (publish_slug ~ '^[a-z0-9][a-z0-9-]{3,55}$'),
  template_slug text not null,
  public_content jsonb not null default '{}'::jsonb,
  provider_transaction_id text,
  provider_state integer,
  provider_reason integer,
  provider_created_ms bigint,
  provider_performed_ms bigint,
  provider_cancelled_ms bigint,
  provider_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '12 hours'),
  paid_at timestamptz,
  cancelled_at timestamptz
);
alter table public.payment_orders enable row level security;
create index if not exists payment_orders_owner_created_idx on public.payment_orders(owner_id, created_at desc);
create index if not exists payment_orders_project_status_idx on public.payment_orders(project_id, status);
create unique index if not exists payment_orders_provider_tx_uidx on public.payment_orders(provider, provider_transaction_id) where provider_transaction_id is not null;
create unique index if not exists payment_orders_one_paid_project_uidx on public.payment_orders(project_id) where status='paid';
drop policy if exists "payment orders owner read" on public.payment_orders;
create policy "payment orders owner read" on public.payment_orders for select to authenticated using ((select auth.uid()) = owner_id);
grant select on public.payment_orders to authenticated;
revoke insert, update, delete on public.payment_orders from anon, authenticated;

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.payment_orders(id) on delete cascade,
  provider text not null,
  event_type text not null,
  provider_transaction_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.payment_events enable row level security;
revoke all on public.payment_events from anon, authenticated;
create index if not exists payment_events_order_created_idx on public.payment_events(order_id, created_at);

drop policy if exists "published sites owner insert" on public.published_sites;
drop policy if exists "published sites owner update" on public.published_sites;
revoke insert, update on public.published_sites from authenticated, anon;
revoke execute on function public.emora_publish_project(uuid,text) from public, anon, authenticated;

create or replace function public.emora_finalize_paid_order(
  p_order_id uuid,
  p_provider_transaction_id text,
  p_provider_payload jsonb default '{}'::jsonb
) returns table(project_id uuid, slug text)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  o public.payment_orders%rowtype;
begin
  select * into o from public.payment_orders where id=p_order_id for update;
  if not found then raise exception 'Payment order not found'; end if;
  if o.status='paid' then
    if o.provider_transaction_id is distinct from p_provider_transaction_id then raise exception 'Payment transaction mismatch'; end if;
    return query select o.project_id,o.publish_slug;
    return;
  end if;
  if o.status<>'pending' then raise exception 'Payment order is not pending'; end if;
  if o.expires_at < now() then
    update public.payment_orders set status='expired',updated_at=now() where id=o.id;
    raise exception 'Payment order expired';
  end if;
  if exists(select 1 from public.payment_orders x where x.provider=o.provider and x.provider_transaction_id=p_provider_transaction_id and x.id<>o.id) then raise exception 'Provider transaction already used'; end if;
  update public.payment_orders
    set status='paid',provider_transaction_id=p_provider_transaction_id,
        provider_state=coalesce(provider_state,2),provider_payload=coalesce(p_provider_payload,'{}'::jsonb),
        paid_at=coalesce(paid_at,now()),updated_at=now()
    where id=o.id;
  insert into public.published_sites(project_id,slug,template_slug,public_content,is_active,published_at,updated_at)
    values(o.project_id,o.publish_slug,o.template_slug,o.public_content,true,now(),now())
  on conflict (project_id) do update set
    slug=excluded.slug,template_slug=excluded.template_slug,public_content=excluded.public_content,
    is_active=true,published_at=now(),updated_at=now();
  update public.projects set status='published',slug=o.publish_slug,published_at=now(),updated_at=now() where id=o.project_id;
  insert into public.payment_events(order_id,provider,event_type,provider_transaction_id,payload)
    values(o.id,o.provider,'paid',p_provider_transaction_id,coalesce(p_provider_payload,'{}'::jsonb));
  return query select o.project_id,o.publish_slug;
end $function$;
revoke all on function public.emora_finalize_paid_order(uuid,text,jsonb) from public, anon, authenticated;
grant execute on function public.emora_finalize_paid_order(uuid,text,jsonb) to service_role;

create or replace function public.emora_unpublish_project(p_project uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if (select auth.uid()) is null then raise exception 'Login required'; end if;
  if not exists(select 1 from public.projects p where p.id=p_project and p.owner_id=(select auth.uid())) then raise exception 'Project not found'; end if;
  update public.published_sites set is_active=false,updated_at=now() where project_id=p_project;
  if not found then raise exception 'No published site owned by this user'; end if;
  update public.projects set status='draft',updated_at=now() where id=p_project and owner_id=(select auth.uid());
  return true;
end $function$;
revoke all on function public.emora_unpublish_project(uuid) from public, anon;
grant execute on function public.emora_unpublish_project(uuid) to authenticated;
