alter table public.payments
  add column if not exists provider_prepare_id bigint generated by default as identity,
  add column if not exists provider_created_at_ms bigint,
  add column if not exists provider_performed_at_ms bigint,
  add column if not exists provider_cancelled_at_ms bigint,
  add column if not exists provider_account jsonb not null default '{}'::jsonb;

create unique index if not exists payments_provider_prepare_id_uq on public.payments(provider_prepare_id);
create index if not exists payments_provider_created_ms_idx on public.payments(provider,provider_created_at_ms);
