alter table public.payment_orders add column if not exists provider_prepare_id bigint generated by default as identity;
create unique index if not exists payment_orders_provider_prepare_uidx on public.payment_orders(provider_prepare_id);

drop policy if exists "published sites owner deactivate" on public.published_sites;
create policy "published sites owner deactivate" on public.published_sites
for update to authenticated
using (exists(select 1 from public.projects p where p.id=published_sites.project_id and p.owner_id=(select auth.uid())))
with check (is_active=false and exists(select 1 from public.projects p where p.id=published_sites.project_id and p.owner_id=(select auth.uid())));
grant update(is_active,updated_at) on public.published_sites to authenticated;

create or replace function public.emora_unpublish_project(p_project uuid)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $function$
begin
  if (select auth.uid()) is null then raise exception 'Login required'; end if;
  update public.published_sites set is_active=false,updated_at=now()
    where project_id=p_project and exists(select 1 from public.projects p where p.id=p_project and p.owner_id=(select auth.uid()));
  if not found then raise exception 'No published site owned by this user'; end if;
  update public.projects set status='draft',updated_at=now() where id=p_project and owner_id=(select auth.uid());
  return true;
end $function$;
revoke all on function public.emora_unpublish_project(uuid) from public, anon;
grant execute on function public.emora_unpublish_project(uuid) to authenticated;
